---
title: "Análisis Exploratorio de las ventas de 17.000 juegos"
format: html
editor: visual
lang: es
theme: darkly
toc: true
---

# Introducción

En la historia, hemos visto cómo los videojuegos han ido evolucionando a medida que transcurre el tiempo. Podemos ver el cómo van mejorando sus motores gráficos, como también el catálogo de géneros de estos.

Gracias a esto, las preferencias de los usuarios también han ido variando. En los inicios solo había unos pocos juegos que se vendían masivamente y eran casi la única alternativa para entretenerse virtualmente. Ahora, dado a la masificación de la industria de los videojuegos, existen una gran cantidad de géneros y formatos para estos.

En este reporte analizaremos una base de datos la cual contiene son videojuegos con ventas mayores a 100.000 copias al rededor del mundo, y están recopilados desde el año 1980 hasta el 2016.

Por lo cual, el objetivo de este análisis exploratorio es el entender cómo los datos están distribuidos e idealmente el poder generar conocimiento para la toma de decisiones en el futuro. Por otra parte, el enfoque de este análisis es el explorar lo más posible los datos de la manera más simple, intuitiva e informativa. Para ello, este proyecto se dividirá en 2 partes.

-   Análisis descriptivo: Acá analizaremos datos relevantes tales como las medidas de tendencia central, gráficos de dispersión, entre otros.

-   Análisis exploratorio: En esta sección nos adentraremos en los datos y responderemos algunas preguntas, tales como

    -   ¿Cuál es el juego más vendido en el mundo?

    -   ¿Cuál es el número de ventas por plataforma?

    -   ¿Cuántas copias se venden al año?

entre otras preguntas que surgirán al analizar los datos.
